### PR TITLE
Fix for talend-spatial/talend-spatial#77

### PR DESCRIPTION
**Pull request by jonescc**
Import core packages instead on including them and exporting them
to prevent issues loading them from two sources

### CODE REVIEW

**Comment by jonescc** [comment]
This resolves my problems with workbench auto saves on the installs I was having a problem with but not sure what the impact is on the rest of the plugin and wasn't sure how to test more rigorously.  Happy to provide further information/support as required to get this fixed.

**Comment by jonescc** [comment]
Unable to break this with further testing.   If there's a test suite that can be run to regression test these changes let me know.

**Comment by jonescc** [comment]
Included missing commit fixing manifest errors.  Updated org.talend.sdi.jar with generated versions.

Updated zip file including this fix can be found at https://s3-ap-southeast-2.amazonaws.com/imos-binary/static/talend/TOS-Spatial-7.1.1-patch-2.zip.

Tested using docker (https://github.com/jonescc/tos-7.1.1-docker/tree/tos-spatial-fix-demo)

**Comment by jonescc** [comment]
Updated docker branches above and in https://github.com/talend-spatial/talend-spatial/issues/77 with instructions for more reliable xserver connection.    Should be relatively easy to see problem still occurring when upgrading org.eclipse.emf.common to core version and being fixed with changes made in this PR.

**Comment by jonescc** [comment]
I've updated this PR to fix an issue I had building spatial projects.

common-2.6.0.jar, ecore-2.6.1.jar and xsd-2.6.0.jar need to stay in the lib directory as this is where they are sourced from when building projects.  Only the manifest changes are relevant as they control where the osgi bundle loads these classes from during bundle execution.

I've rebuilt https://s3-ap-southeast-2.amazonaws.com/imos-binary/static/talend/TOS-Spatial-7.1.1-patch-2.zip from the updated pull request and retested (now including building jobs).

**Comment by fxprunayre** [comment]
Thanks a lot Craig, so do you think I can push you build as a 7.1.1 build then ? I could build a new one, but busy on other topics (... I'm looking for a quick & easy options). Thanks for the feedback and in depth checks of what was happening.

**Comment by jonescc** [comment]
Yes.  If you're happy with the way I built it there shouldn't be any problem using that build.

**Comment by fxprunayre** [comment]
I pushed it on sourceforge. Thanks Craig.

**Pull request merged**
