### PR TITLE
Dockerfile and instructions for use

### PR DESCRIPTION
**Pull request by archaeogeek**
- Added clean instructions for building and using a docker image for Talend and Talend Spatial 7.4 release, based on a headless ubuntu server. 
- Added a section to the Install instructions to direct people to the main readme in the docker folder

### CODE REVIEW

**Comment by archaeogeek** [comment]
Hopefully helps with https://github.com/talend-spatial/talend-spatial/issues/87

**Review by fxprunayre — COMMENTED** [review]
Starts fine, but I had to manually add

```
osgi.bundles=org.eclipse.equinox.simpleconfigurator@1\:start,org.eclipse.compare.win32@4,org.eclipse.core.filesystem.linux.x86_64@4,org.eclipse.core.filesystem.macosx@4,org.eclipse.core.filesystem.win32.x86_64@4,org.eclipse.core.net.linux.x86_64@4,org.eclipse.core.net.win32.x86_64@4,org.eclipse.core.resources.win32.x86_64@4,org.eclipse.e4.ui.swt.gtk@4,org.eclipse.e4.ui.workbench.renderers.swt.cocoa@4,org.eclipse.equinox.launcher.cocoa.macosx.x86_64@4,org.eclipse.equinox.launcher.gtk.linux.x86_64@4,org.eclipse.equinox.launcher.win32.win32.x86_64@4,org.eclipse.equinox.security.linux.x86_64@4,org.eclipse.equinox.security.macosx@4,org.eclipse.equinox.security.win32.x86_64@4,org.eclipse.gmf.runtime.common.ui.printing.win32@4,org.eclipse.jdt.launching.macosx@4,org.eclipse.jdt.launching.ui.macosx@4,org.eclipse.swt.cocoa.macosx.x86_64@4,org.eclipse.swt.gtk.linux.x86_64@4,org.eclipse.swt.win32.win32.x86_64@4,org.eclipse.ui.cocoa@4,org.eclipse.ui.win32@4,org.talend.libraries.sdi-7.4.1@4,org.talend.sdi.designer.components-7.4.1@4,org.talend.sdi.designer.routines-7.4.1@4,org.talend.sdi.repository.ui.actions.metadata-7.4.1@4,org.talend.sdi.repository.ui.actions.metadata.ogr-7.4.1@4,org.talend.sdi.workspace.spatial-7.4.1@4 
```

in `configuration/config.ini` to have the component in the palette.

For you it was working on first start without this step ?

**Comment by archaeogeek** [comment]
I have a docker-compose file that adds config.ini as a volume override. I'm not sure how else to do it...

**Comment by fxprunayre** [comment]
Indeed that sounds the way to do (not a docker expert). Could you add this here too ? or we just update the doc to tell users to add that line in the config.ini ?

**Comment by archaeogeek** [comment]
@fxprunayre try this

**Review by fxprunayre — APPROVED** [review]

**Comment by fxprunayre** [comment]
Good to have this easy way to startup with a working GDAL setup. Thanks @archaeogeek

**Pull request merged**
